# This file is part of the Next.js app repository. for testing the deployment process.
name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v4
    - run: docker build . -t  pankajdocker1977/next-js-app
    - run: echo 'India@1234' | docker login -u pankajdocker1977 --password-stdin
 
    - run: docker push  pankajdocker1977/next-js-app:latest